### ISSUE TITLE
USER STORY: As a user, I would like to be able to collapse and reveal assignments in the "due" menu.

### ISSUE THREAD

**Issue by didymusbenson** [byuitechops/what-if-calculator#7]
Requirements: Add a "hide" button (indicated with "-"?) to each assignment row. At the top of the frame there will be a message with "N assignments hidden - Display hidden assignments" so that I can bring them back. 

Justification (example): I'm enrolled in a CIT course that has discussion boards and dropboxes that I do not need to use. I handle the discussion and file submission in person. I want to be able to "ignore" those assignments.

**Comment by tallroids** [comment]
WIP
