### ISSUE TITLE
USER STORY: As a user, I would like to be able to see what is due today.

### ISSUE THREAD

**Issue by didymusbenson** [byuitechops/what-if-calculator#8]
Requirements: Add a "due today" button somewhere in the tool that will toggle between assignments due today and all assignments. Consider giving this other options as well, such as switching between Today/This Week/All. 

Justification: As a student I do not want to have to dig to find what things are due today. Some of my assignments show up out of order of due date anyway, so it would be helpful to organize by when they are due.

**Comment by tallroids** [comment]
Implemented Highlighting instead
